services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: funk
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
    volumes: 
      - ./schema:/docker-entrypoint-initdb.d
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: funk
volumes:
  wordpress:
  db: